const SUPABASE_URL = 'https://bqioqdpoyusdnxgdvqup.supabase.co';
const SUPABASE_KEY = 'sb_publishable_MmFgDGBXNyitTBYLKIFe5g_-xj4vX8n';
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
let hostels = [];

function normalizeHostel(row){return {id:row.id,name:row.name,city:row.destination,type:row.hostel_type,price:Number(row.price_per_night),rating:Number(row.rating||4.5),image:row.image_url,description:row.description,amenities:row.amenities||[]};}
async function loadHostels(){const list=document.getElementById('hostelList');list.innerHTML='<div class="loading-state">🔄 Finding hostels across India...</div>';const {data,error}=await db.from('hostels').select('*').order('rating',{ascending:false});if(error){console.error(error);list.innerHTML='<div class="loading-state">⚠️ Could not load hostels. Please refresh.</div>';return;}hostels=(data||[]).map(normalizeHostel);renderHostels(hostels);}
function renderHostels(list=hostels){const el=document.getElementById('hostelList'),none=document.getElementById('noResults');el.innerHTML='';if(!list.length){none.style.display='block';return;}none.style.display='none';list.forEach(h=>{const c=document.createElement('div');c.className='hostel-card';c.innerHTML=`<div class="hostel-image" style="background-image:url('${h.image}')"><div class="rating">⭐ ${h.rating.toFixed(1)}</div></div><div class="card-content"><span class="tag">${getTypeName(h.type)}</span><h3>${escapeHtml(h.name)}</h3><p class="location">📍 ${escapeHtml(h.city)}, India</p><p class="description">${escapeHtml(h.description||'Backpacker-friendly stay with social spaces.')}</p><div class="amenities">${h.amenities.map(a=>`<span class="amenity">${escapeHtml(a)}</span>`).join('')}</div><div class="card-bottom"><div class="price">₹${h.price}<small> / night</small></div><button class="view-btn" onclick="viewDetailsById(${h.id})">View</button></div></div>`;el.appendChild(c);});}
function getTypeName(t){return t==='male'?'Male Dorm':t==='female'?'Female Dorm':'Mixed Dorm';}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function getFilteredHostels(){const q=document.getElementById('locationInput').value.trim().toLowerCase(),type=document.getElementById('genderFilter').value,price=document.getElementById('priceFilter').value,max=price==='all'?Infinity:Number(price);return hostels.filter(h=>(!q||h.city.toLowerCase().includes(q)||h.name.toLowerCase().includes(q))&&(type==='all'||h.type===type)&&h.price<=max);}
function searchHostels(){renderHostels(getFilteredHostels());document.getElementById('hostels').scrollIntoView({behavior:'smooth'});}
function filterByPrice(){renderHostels(getFilteredHostels());}
function quickSearch(city){document.getElementById('locationInput').value=city;searchHostels();}
function viewDetailsById(id){const h=hostels.find(x=>Number(x.id)===Number(id));if(h)viewDetails(h.name);}
function viewDetails(name){const h=hostels.find(x=>x.name===name);if(!h)return;document.getElementById('detailModal')?.remove();const modal=document.createElement('div');modal.id='detailModal';modal.className='modal-backdrop';modal.innerHTML=`<div class="detail-modal"><button class="modal-close">×</button><img src="${h.image}" alt="${escapeHtml(h.name)}"><div class="modal-body"><span class="tag">${getTypeName(h.type)}</span><h2>${escapeHtml(h.name)}</h2><p class="location">📍 ${escapeHtml(h.city)}, India</p><div class="modal-rating">⭐ ${h.rating.toFixed(1)} · Highly rated</div><p>${escapeHtml(h.description||'')}</p><div class="modal-amenities">${h.amenities.map(a=>`<span>${escapeHtml(a)}</span>`).join('')}</div><div class="modal-bottom"><strong>₹${h.price}<small> / night</small></strong><button class="book-btn" id="availabilityBtn">Check Availability</button></div></div></div>`;document.body.appendChild(modal);modal.querySelector('.modal-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove();};modal.querySelector('#availabilityBtn').onclick=()=>openBooking(h);}
function openBooking(h){document.getElementById('bookingModal')?.remove();const modal=document.createElement('div');modal.id='bookingModal';modal.className='modal-backdrop';const today=new Date().toISOString().split('T')[0];modal.innerHTML=`<div class="login-modal booking-modal"><button class="modal-close">×</button><div class="login-logo">🛏️</div><h2>Book your stay</h2><p><b>${escapeHtml(h.name)}</b><br>📍 ${escapeHtml(h.city)} · ₹${h.price}/night</p><input id="guestName" placeholder="Full name" autocomplete="name"><input id="guestEmail" placeholder="Email address" type="email" autocomplete="email"><label>Check-in</label><input id="checkIn" type="date" min="${today}"><label>Check-out</label><input id="checkOut" type="date" min="${today}"><label>Guests</label><input id="guestCount" type="number" min="1" value="1"><div id="bookingTotal" class="booking-total">Total: ₹${h.price}</div><p id="bookingMessage" class="booking-message"></p><button id="confirmBooking" class="book-btn">Confirm Booking</button></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.modal-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close();};const updateTotal=()=>{const a=new Date(document.getElementById('checkIn').value),b=new Date(document.getElementById('checkOut').value),g=Math.max(1,Number(document.getElementById('guestCount').value)||1);const nights=(b-a)/86400000;if(nights>0)document.getElementById('bookingTotal').textContent=`Total: ₹${h.price*nights*g} (${nights} night${nights>1?'s':''} × ${g} guest${g>1?'s':''})`;else document.getElementById('bookingTotal').textContent=`Total: ₹${h.price}`;};['checkIn','checkOut','guestCount'].forEach(id=>document.getElementById(id).addEventListener('change',updateTotal));document.getElementById('confirmBooking').onclick=async()=>{const name=document.getElementById('guestName').value.trim(),email=document.getElementById('guestEmail').value.trim(),ci=document.getElementById('checkIn').value,co=document.getElementById('checkOut').value,guests=Math.max(1,Number(document.getElementById('guestCount').value)||1),msg=document.getElementById('bookingMessage');if(!name||!email||!ci||!co)return msg.textContent='Please fill all booking details.';if(!/^\S+@\S+\.\S+$/.test(email))return msg.textContent='Please enter a valid email.';const nights=(new Date(co)-new Date(ci))/86400000;if(nights<=0)return msg.textContent='Check-out must be after check-in.';const total=h.price*nights*guests;const {error}=await db.from('bookings').insert({hostel_id:h.id,guest_name:name,guest_email:email,check_in:ci,check_out:co,guests,total_amount:total,status:'confirmed'});if(error){console.error(error);msg.textContent='Booking could not be saved. Please try again.';return;}msg.innerHTML=`✅ <b>Booking confirmed!</b><br>₹${total} · ${nights} night${nights>1?'s':''}<br>Your booking has been saved.`;document.getElementById('confirmBooking').disabled=true;};}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('locationInput').addEventListener('keydown',e=>{if(e.key==='Enter')searchHostels();});document.getElementById('genderFilter').addEventListener('change',searchHostels);loadHostels();});